### ISSUE TITLE
Connect over USB serial

### ISSUE THREAD

**Issue by azvero** [AngryApostrophe/Clout#8]
It would be very handy to be able to connect to a machine over USB serial rather than Wi-Fi.  I don't believe this is currently possible.  Makera's controller has both options.

P.S. Thanks for what looks like a great tool (I've only just discovered it).

**Comment by AngryApostrophe** [comment]
Thanks for the suggestion. I've been pretty busy with work but I'll push this up to the top of the list.

**Comment by AngryApostrophe** [comment]
Initial serial port capability has been added.  Please let me know how it's working for you, or if you see any bugs.  Testing this is a PITA for me since my dev computer isn't near my Carvera to plug in, but it seems to be working alright.

**Comment by zvea** [comment]
Thanks!  On my machine I found that I had to explicitly configure the serial port to use 115200-8-1-N to get this to work.  I just sent a PR your way.  Otherwise everything seems to be working great.
